
// ******************************************************** //
// THIS CODE WAS AUTO GENERATED BY 'AliasesConfigGenerator' //
// ******************************************************** //

using System;
using System.Collections.Generic;
using UnityEngine;

namespace Modules.ReferenceDb_Public
{
    //
    // All variables here are supposed to be used at runtime and are subject to change after refreshing ReferenceDB.
    // DO NOT serialize any field value directly. Use string aliases instead.
    //

    public class ReferenceDbAliasesConfig
    {   
    
		// Characters //

		public const int Character_Player = 0;
		public const int Character_Test_AI = 1;

		// Dictionaries //

		// *****************************
		// GetId 
		// *****************************
		public int GetId(string _alias)
		{
		   bool success = dictAliasToId.TryGetValue(_alias, out int result);
		   if(!success)
		   {
		        Debug.Assert(false, $"Alias={_alias} was not found at ReferenceDb!");
		   } 
		   return result;
		}

		private readonly Dictionary<string, int> dictAliasToId = new()
		{
		    { "Character_Player", 0 },
		    { "Character_Test_AI", 1 },

		};

    }
    
    // CATEGORY ENUMS:
    /// <summary>
    /// Elements of 'CHARACTERS' category.
    /// DO NOT serialize this enum.
    /// </summary>
    public enum CATEGORY_CHARACTERS
    {
		Character_Player = 0,
		Character_Test_AI = 1,

    }
}
