
// ******************************************************** //
// THIS CODE WAS AUTO GENERATED BY 'AliasesConfigGenerator' //
// ******************************************************** //

using System;
using System.Collections.Generic;
using UnityEngine;

namespace Modules.ReferenceDb_Public
{
    //
    // All variables here are supposed to be used at runtime and are subject to change after refreshing ReferenceDB.
    // DO NOT serialize any field value directly. Use string aliases instead.
    //

    public class ReferenceDbAliasesConfig
    {   
    
		// Dictionaries //

		// *****************************
		// GetId 
		// *****************************
		public int GetId(string _alias)
		{
		   bool success = dictAliasToId.TryGetValue(_alias, out int result);
		   if(!success)
		   {
		        Debug.Assert(false, $"Alias={_alias} was not found at ReferenceDb!");
		   } 
		   return result;
		}

		private readonly Dictionary<string, int> dictAliasToId = new()
		{

		};

    }
    
    // CATEGORY ENUMS:
}
