
// ******************************************************** //
// THIS CODE WAS AUTO GENERATED BY 'ScreensConfigGenerator' //
// ******************************************************** //

namespace Modules.UI.UIController_Public
{
        public enum ScreenType
        {
            UNDEFINED = -1,
        	HUD = 0,
	Upgrades = 1,

        }
}
